#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask 'veilid-server.service' >/dev/null || true
    fi
elif [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge 'veilid-server.service' >/dev/null || true
        deb-systemd-helper unmask 'veilid-server.service' >/dev/null || true
    fi
    rm -rf /var/db/veilid-server
fi
